from __future__ import annotations

from typing import Any, Dict, List

from .types import MedDocument, PatternReport


class ExplanationEngine:
    def build(
        self,
        query: str,
        model_payload: Dict[str, Any],
        patterns: PatternReport,
        documents: List[MedDocument],
    ) -> Dict[str, Any]:
        top_terms = [item["term"] for item in patterns.top_terms[:8]]
        recursive_terms = [item["term"] for item in patterns.recursive_signals[:6]]
        top_refs = [doc.endpoint_url for doc in documents[:8]]

        summary = (
            "This result is generated by combining the user query with medframework-derived "
            "patterns and recursive signals, then mapping those signals into a structured "
            "discovery response."
        )
        rationale = [
            f"Top recurring signals: {', '.join(top_terms) if top_terms else 'none'}",
            f"Recursive cross-document terms: {', '.join(recursive_terms) if recursive_terms else 'none'}",
            "Recommendations should be validated with wet-lab controls and domain review before use.",
        ]
        return {
            "summary": summary,
            "query_focus": query,
            "rationale": rationale,
            "supporting_endpoints": top_refs,
            "model_output_keys": sorted(list(model_payload.keys())),
        }
